# Add a function called summary() to your currency.py module, which displays on the screen some information 
# generated by the functions we have developed so far, organized in a neat table.

from currency import summary

value = float(input('Digite um valor em R$'))
summary(value, 80, 25)